name: 🐛 バグ報告
description: GameMacroAssistant で発生したバグを報告する
title: "[BUG] バグの概要"
labels: ["bug", "needs-triage"]
projects: ["GameMacroAssistant"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 バグ報告
        GameMacroAssistant で発生したバグを詳しく報告してください。再現手順と期待する動作を明確に記載してください。

  - type: dropdown
    id: severity
    attributes:
      label: 重要度
      description: バグの重要度を選択してください
      options:
        - Critical (アプリケーションがクラッシュする)
        - High (主要機能が動作しない)
        - Medium (一部機能に問題がある)
        - Low (軽微な問題・UI不具合)
      default: 2
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 影響コンポーネント
      description: 問題が発生している機能を選択してください
      options:
        - マクロ記録
        - ビジュアルエディタ
        - マクロ実行
        - 画像マッチング
        - ファイル保存・読込
        - 設定画面
        - UI全般
        - パフォーマンス
        - その他
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: バグの説明
      description: 発生している問題を詳しく説明してください
      placeholder: |
        マクロ記録中にマウスクリックが正常に記録されない問題が発生しています。
        クリック操作を行っても、エディタ画面に表示されません。
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 再現手順
      description: バグを再現するための詳細な手順を記載してください
      placeholder: |
        1. GameMacroAssistant を起動
        2. メイン画面の「記録開始」ボタンをクリック
        3. デスクトップ上の任意の場所をマウス左クリック
        4. ESCキーで記録停止
        5. ビジュアルエディタを確認
        
        期待する結果: クリック操作がブロックとして表示される
        実際の結果: ブロックが追加されない
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 期待する動作
      description: 正常に動作する場合にどのような結果になるべきかを記載してください
      placeholder: |
        マウスクリック操作が記録され、ビジュアルエディタにクリックブロックが表示される
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 実際の動作
      description: 現在発生している実際の動作を記載してください
      placeholder: |
        マウスクリック操作が記録されず、ビジュアルエディタに何も表示されない
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: アプリケーションバージョン
      description: 使用しているGameMacroAssistantのバージョン
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS バージョン
      description: 使用しているWindowsのバージョン
      placeholder: "Windows 11 22H2"
    validations:
      required: true

  - type: input
    id: dotnet_version
    attributes:
      label: .NET バージョン
      description: インストールされている.NETのバージョン (dotnet --version で確認)
      placeholder: "8.0.100"
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: エラーログ
      description: |
        関連するエラーメッセージやログファイルの内容を貼り付けてください
        ログファイル場所: %APPDATA%\GameMacroAssistant\Logs\
      placeholder: |
        2024-01-15 10:30:45 [ERROR] MacroRecorder: Failed to capture mouse click
        System.InvalidOperationException: Input hook not initialized
           at GameMacroAssistant.Core.Services.InputHookService.CaptureMouseClick()
           at GameMacroAssistant.Core.Services.MacroRecorder.OnMouseClick()
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: |
        バグの状況を示すスクリーンショットがあれば添付してください
        画像をドラッグ&ドロップまたはクリップボードから貼り付けできます
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: 発生頻度
      description: バグがどの程度の頻度で発生するかを選択してください
      options:
        - 毎回 (100%)
        - ほとんど (80%以上)
        - 時々 (50%程度)
        - 稀に (20%以下)
        - 一度だけ
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: 回避方法
      description: 一時的な回避方法がある場合は記載してください
      placeholder: |
        アプリケーションを再起動すると一時的に問題が解決します
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 追加情報
      description: その他、バグ修正に役立つ情報があれば記載してください
      placeholder: |
        - 特定のアプリケーション使用時にのみ発生
        - マルチモニター環境で発生
        - 高DPI設定で発生
    validations:
      required: false

  - type: checkboxes
    id: diagnostic_info
    attributes:
      label: 診断情報収集協力
      description: バグ修正のために追加情報の提供にご協力いただけますか？
      options:
        - label: ログファイルの詳細情報を提供できます
          required: false
        - label: クラッシュダンプの送信に同意します
          required: false
        - label: 追加テストへの協力が可能です
          required: false